name: GitHub Readme Guestbook

on:
  issues:
    types: [opened, closed, reopened, deleted, edited]

jobs:
  update_guestbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Update guestbook
        uses: muety/readme-guestbook@v1.0.9
        with:
          token: ${{ secrets.GH_TOKEN }}
          max_entries: 30
